"""
This module defines all conversation states used in the bot.
It's a separate file to avoid circular imports between handlers.
"""

# Define conversation states for tracking
START = 0
REGISTER = 1
ROLE = 2
EMPLOYER_MENU = 3
CATEGORY = 4
SUBCATEGORY = 5
DESCRIPTION = 6
LOCATION_TYPE = 7
LOCATION_INPUT = 8
DETAILS = 9
DETAILS_FILES = 10
DETAILS_DATE = 11
DETAILS_DEADLINE = 12
DETAILS_BUDGET = 13
DETAILS_QUANTITY = 14
SUBMIT = 15
VIEW_PROJECTS = 16
PROJECT_ACTIONS = 17
CHANGE_PHONE = 18
VERIFY_CODE = 19

# Map state numbers to names for better logging
STATE_NAMES = {
    START: "START",
    REGISTER: "REGISTER",
    ROLE: "ROLE",
    EMPLOYER_MENU: "EMPLOYER_MENU",
    CATEGORY: "CATEGORY",
    SUBCATEGORY: "SUBCATEGORY",
    DESCRIPTION: "DESCRIPTION",
    LOCATION_TYPE: "LOCATION_TYPE",
    LOCATION_INPUT: "LOCATION_INPUT",
    DETAILS: "DETAILS",
    DETAILS_FILES: "DETAILS_FILES",
    DETAILS_DATE: "DETAILS_DATE",
    DETAILS_DEADLINE: "DETAILS_DEADLINE",
    DETAILS_BUDGET: "DETAILS_BUDGET",
    DETAILS_QUANTITY: "DETAILS_QUANTITY",
    SUBMIT: "SUBMIT",
    VIEW_PROJECTS: "VIEW_PROJECTS",
    PROJECT_ACTIONS: "PROJECT_ACTIONS",
    CHANGE_PHONE: "CHANGE_PHONE",
    VERIFY_CODE: "VERIFY_CODE"
}